# database
spring.datasource.url=jdbc:mysql://localhost:3306/chat_app
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.generate-ddl=true

# tomcat
server.port=8080

# file upload
file.upload.path=src/main/resources/multimedia

# default image urls
default.user.avatar.code=mark.png
default.group.avatar.code=elon.png
